### ISSUE TITLE
任务列表

### ISSUE THREAD

**Issue by OlingCat** [rust-lang-cn/rustc-guide#3]
# 任务列表

## 认领方式

请译者发起新 Issue，并将 assignee 设为自己。

以下为任务列表，取自
- [x] [SUMMARY.md](../blob/master/src-zh/SUMMARY.md) @OlingCat  #5 ：
- [ ] [About this guide](../blob/master/src-zh/about-this-guide.md)

---

## 第一部分

- [ ] [Part 1: Building, debugging, and contributing to Rustc](../blob/master/src-zh/part-1-intro.md)
- [ ] [About the compiler team](../blob/master/src-zh/compiler-team.md)
- [ ] [How to Build and Run the Compiler](../blob/master/src-zh/how-to-build-and-run.md)
    - [ ] [Build and Install distribution artifacts](../blob/master/src-zh/build-install-distribution-artifacts.md)
    - [ ] [Documenting Compiler](../blob/master/src-zh/compiler-documenting.md)
- [ ] [The compiler testing framework](../blob/master/src-zh/tests/intro.md)
    - [ ] [Running tests](../blob/master/src-zh/tests/running.md)
    - [ ] [Adding new tests](../blob/master/src-zh/tests/adding.md)
    - [ ] [Using `compiletest` + commands to control test execution](../blob/master/src-zh/compiletest.md)
- [ ] [Walkthrough: a typical contribution](../blob/master/src-zh/walkthrough.md)
- [ ] [Implementing new features](../blob/master/src-zh/implementing_new_features.md)
- [ ] [Stabilizing Features](../blob/master/src-zh/stabilization_guide.md)
- [ ] [Debugging the Compiler](../blob/master/src-zh/compiler-debugging.md)
- [ ] [Profiling the compiler](../blob/master/src-zh/profiling.md)
    - [ ] [with the linux perf tool](../blob/master/src-zh/profiling/with_perf.md)
- [ ] [Coding conventions](../blob/master/src-zh/conventions.md)
- [ ] [crates.io Dependencies](../blob/master/src-zh/crates-io.md)
- [ ] [Emitting Errors and other Diagnostics](diagnostics.md)
    - [ ] [JSON diagnostic format](diagnostics/json-format.md)

## 第二部分

- [ ] [Part 2: How rustc works](../blob/master/src-zh/part-2-intro.md)
- [ ] [High-level overview of the compiler source](../blob/master/src-zh/high-level-overview.md)
- [ ] [The Rustc Driver and Interface](../blob/master/src-zh/rustc-driver.md)
    - [ ] [Rustdoc](../blob/master/src-zh/rustdoc.md)
- [ ] [Queries: demand-driven compilation](../blob/master/src-zh/query.md)
    - [ ] [The Query Evaluation Model in Detail](../blob/master/src-zh/queries/query-evaluation-model-in-detail.md)
    - [ ] [Incremental compilation](../blob/master/src-zh/queries/incremental-compilation.md)
    - [ ] [Incremental compilation In Detail](../blob/master/src-zh/queries/incremental-compilation-in-detail.md)
    - [ ] [Debugging and Testing](../blob/master/src-zh/incrcomp-debugging.md)
- [ ] [The parser](../blob/master/src-zh/the-parser.md)
- [ ] [`#[test]` Implementation](../blob/master/src-zh/test-implementation.md)
- [ ] [Macro expansion](../blob/master/src-zh/macro-expansion.md)
- [ ] [Name resolution](../blob/master/src-zh/name-resolution.md)
- [ ] [The HIR (High-level IR)](../blob/master/src-zh/hir.md)
    - [ ] [Lowering AST to HIR](../blob/master/src-zh/lowering.md)
    - [ ] [Debugging](../blob/master/src-zh/hir-debugging.md)
- [ ] [The `ty` module: representing types](../blob/master/src-zh/ty.md)
- [ ] [Kinds](../blob/master/src-zh/kinds.md)
- [ ] [Type inference](../blob/master/src-zh/type-inference.md)
- [ ] [Trait solving (old-style)](../blob/master/src-zh/traits/resolution.md)
    - [ ] [Higher-ranked trait bounds](../blob/master/src-zh/traits/hrtb.md)
    - [ ] [Caching subtleties](../blob/master/src-zh/traits/caching.md)
    - [ ] [Specialization](../blob/master/src-zh/traits/specialization.md)
- [ ] [Trait solving (new-style)](../blob/master/src-zh/traits/index.md)
    - [ ] [Lowering to logic](../blob/master/src-zh/traits/lowering-to-logic.md)
  - [ ] [Goals and clauses](../blob/master/src-zh/traits/goals-and-clauses.md)
  - [ ] [Equality and associated types](../blob/master/src-zh/traits/associated-types.md)
  - [ ] [Implied bounds](../blob/master/src-zh/traits/implied-bounds.md)
  - [ ] [Region constraints](../blob/master/src-zh/traits/regions.md)
  - [ ] [The lowering module in rustc](../blob/master/src-zh/traits/lowering-module.md)
  - [ ] [Lowering rules](../blob/master/src-zh/traits/lowering-rules.md)
  - [ ] [Well-formedness checking](../blob/master/src-zh/traits/wf.md)
    - [ ] [Canonical queries](../blob/master/src-zh/traits/canonical-queries.md)
  - [ ] [Canonicalization](../blob/master/src-zh/traits/canonicalization.md)
    - [ ] [The SLG solver](../blob/master/src-zh/traits/slg.md)
    - [ ] [An Overview of Chalk](../blob/master/src-zh/traits/chalk-overview.md)
    - [ ] [Bibliography](../blob/master/src-zh/traits/bibliography.md)
- [ ] [Type checking](../blob/master/src-zh/type-checking.md)
    - [ ] [Method Lookup](../blob/master/src-zh/method-lookup.md)
    - [ ] [Variance](../blob/master/src-zh/variance.md)
    - [ ] [Existential Types](../blob/master/src-zh/existential-types.md)
- [ ] [The MIR (Mid-level IR)](../blob/master/src-zh/mir/index.md)
    - [ ] [MIR construction](../blob/master/src-zh/mir/construction.md)
    - [ ] [MIR visitor and traversal](../blob/master/src-zh/mir/visitor.md)
    - [ ] [MIR passes: getting the MIR for a function](../blob/master/src-zh/mir/passes.md)
    - [ ] [MIR optimizations](../blob/master/src-zh/mir/optimizations.md)
    - [ ] [Debugging](../blob/master/src-zh/mir/debugging.md)
- [ ] [The borrow checker](../blob/master/src-zh/borrow_check.md)
    - [ ] [Tracking moves and initialization](../blob/master/src-zh/borrow_check/moves_and_initialization.md)
  - [ ] [Move paths](../blob/master/src-zh/borrow_check/moves_and_initialization/move_paths.md)
    - [ ] [MIR type checker](../blob/master/src-zh/borrow_check/type_check.md)
    - [ ] [Region inference](../blob/master/src-zh/borrow_check/region_inference.md)
    - [ ] [Two-phase-borrows](../blob/master/src-zh/borrow_check/two_phase_borrows.md)
- [ ] [Constant evaluation](../blob/master/src-zh/const-eval.md)
    - [ ] [miri const evaluator](../blob/master/src-zh/miri.md)
- [ ] [Parameter Environments](../blob/master/src-zh/param_env.md)
- [ ] [Code Generation](../blob/master/src-zh/codegen.md)
    - [ ] [Updating LLVM](../blob/master/src-zh/codegen/updating-llvm.md)
    - [ ] [Debugging LLVM](../blob/master/src-zh/codegen/debugging.md)
- [ ] [Profile-guided Optimization](../blob/master/src-zh/profile-guided-optimization.md)

## 附录

- [ ] [Appendix A: Stupid Stats](../blob/master/src-zh/appendix/stupid-stats.md)
- [ ] [Appendix B: Background material](../blob/master/src-zh/appendix/background.md) @OlingCat #8 
- [ ] [Appendix C: Glossary](../blob/master/src-zh/appendix/glossary.md) @OlingCat #4
- [ ] [Appendix D: Code Index](../blob/master/src-zh/appendix/code-index.md) @OlingCat #16
- [ ] [Ignore me](../blob/master/src-zh/important-links.md)
